name: CI/CD github pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  runs-on: ubuntu-latest
  build:
    steps:
      - name: checkout repository
      - uses: actions/checkout@v3

      - name: build and deploy
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm install
          npm run predeploy
          npm run deploy