name: CI/CD github pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: build and deploy
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: installing dependencies and pushing to github pages
        run: |
          npm install
          git config --global user.email stephen.adingupu@gmail.com
          git config --global user.name stephen
          npm run predeploy
          npm run deploy
